Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/focal"
  config.vm.network "public_network", ip: "192.168.31.100"
  config.vm.box_check_update = false
  config.vm.hostname = "testing"

  config.vm.provider :virtualbox do |vb, override|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--memory", "32768"]
      vb.customize ["modifyvm", :id, "--cpus", 12]
  end
  
  config.vm.provision "shell", name: "docker", path: "provision/docker.sh"
  config.vm.provision "shell", name: "alias", path: "provision/alias.sh"

  config.ssh.username = "root"
  config.ssh.password = "9527"
end
