global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "127.0.0.1:9090"
        labels:
            job: target_group_1

  - job_name: "static_demo"
    metrics_path: "/"
    params:
     addr: ['172.31.148.52:3999']
     cmd: ['metrics']
    static_configs:
      - targets:
          - '172.31.243.215:8181'

  - job_name: "file_demo"
    metrics_path: "/"
    params:
     addr: ['172.31.148.52:3999']
     cmd: ['metrics']
    file_sd_configs:
      - files:
          - 'targets.json'
