# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets:
          - "traefik:1997"
