[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.metrics]
    address = ":1443"
  [entryPoints.netdata]
    address = ":8081"

[accessLog]
filePath = "/var/log/traefik/acceslog.json"
format = "json"

[log]
filePath = "/var/log/traefik/traefik.json"
format = "json"
level = "DEBUG"

[serversTransport]
maxIdleConnsPerHost = 10

[api]
insecure = false
dashboard = true

[metrics]
 [metrics.prometheus]
  entryPoint = "metrics"
  manualRouting = true
  addServicesLabels = true
  addEntryPointsLabels = true
  buckets = [0.1,0.3,1.2,5.0]

[providers]
 [providers.file]
  directory = "/etc/traefik/rules" # 在指定目录查找配置文件
  watch = true
