version: "3"

services:
  nginx:
    image: nginx
    network_mode: "bridge"
    ports:
      - 9080:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/.autoindex:/.autoindex:ro
      - ${PWD}/:/data:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"