version: "3"

services:
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/sqjian/artifacts:redis
    network_mode: "host"
    container_name: "redis"
    volumes:
      - ${PWD}/config.json:/etc/redis/config.json
      - ${PWD}/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"