name: gitbook

on:
  push:
  schedule:
    - cron: '0 16 */1 * *'

jobs:
  gitbook:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: preprocessing
      run: |
          set -ex
          sudo apt-get install -y dos2unix
          find -type f -name *.sh| xargs dos2unix
          find -type f -name *.sh| xargs chmod +x

    - name: build
      uses: ZanderZhao/gitbook-action@v1.2.4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_dir: gitbook